In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 

[2 3 4 5]


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:]) 

[5 6 7]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1]) 

[5 6]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [6]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) 

[7 8 9]


In [7]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) 

[3 8]


In [8]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]


In [11]:
arr = np.array([[1,5,9],[7,4,2]])

print(arr[0:1, 1])

[5]


In [12]:
arr = np.array([[1,5,9],[7,4,2]])

print(arr[1:1, 1])

[]


In [15]:
arr = np.array([[1,5,9],[7,4,2]])

print(arr[1:2, 1])

[4]


In [16]:
arr = np.array([[1,5,9],[7,4,2]])

print(arr[0:2, 1])

[5 4]


In [17]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


In [19]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [20]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [21]:
x = np.array([5,7,9,1,6])
r = arr.copy()
z = r.view()
r[1] = 69

print(x)
print(r)
print(z)

[5 7 9 1 6]
[42 69  3  4  5]
[42 69  3  4  5]
