In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [2]:
import numpy as np

#arr = np.array([1, 2, 3, 4], ndmin=5)
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], ndmin = 5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3]
    [4 5 6]]

   [[1 2 3]
    [4 5 6]]]]]
number of dimensions : 5


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])
#arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], ndmin = 5)
print(arr)
print('number of dimensions :', arr.ndim)
print(arr[1])

[1 2 3 4]
number of dimensions : 1
2


In [4]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [5]:
ax = np.array([[5,8,7,6],[9,2,4,6]])
print(ax[1, -1])

6


In [6]:
ax = np.array([[5,8,7,6],
               [9,2,4,6],
               [7,9,5,2]])
print(ax[1, 2])

4


In [7]:
ax = np.array([[5,8,7,6],
               [9,2,4,6],
               [7,9,5,2]])
print(ax[2, -2])

5


In [8]:
ax = np.array([[5,8,7,6],
               [9,2,4,6],
               [7,9,5,2]])
print(ax[1:3])

[[9 2 4 6]
 [7 9 5 2]]


In [9]:
ax = np.array([[5,8,7,6],
               [9,2,4,6],
               [7,9,5,2]])
print(ax[::3])

[[5 8 7 6]]


In [10]:
ax = np.array([[5,8,7,6],
               [9,2,4,6],
               [7,9,5,2]])
print(ax[-3:-1])

[[5 8 7 6]
 [9 2 4 6]]


In [11]:
ar = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(ar[1, 1:4])

[7 8 9]
